version: '3'
services:
  connector-passleak:
    image: opencti/connector-passleak:latest
    build: .
    environment:
      - OPENCTI_URL=${OPENCTI_URL:-http://opencti:8080}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID:-9288e3aa-3f94-4505-b31b-69585c47081b}
      - CONNECTOR_NAME=${CONNECTOR_NAME:-Passleak Feed}
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL:-info}
      - PASSLEAK_BASEURL=${PASSLEAK_BASEURL:-https://api.passleak.com/}
      - PASSLEAK_API_KEY=${PASSLEAK_API_KEY}
      - PASSLEAK_INTERVAL=${PASSLEAK_INTERVAL:-86400}
      - PASSLEAK_CONTIMEOUT=${PASSLEAK_CONTIMEOUT:-30}
      - PASSLEAK_READTIMEOUT=${PASSLEAK_READTIMEOUT:-60}
      - PASSLEAK_RETRY=${PASSLEAK_RETRY:-5}
    restart: always
    depends_on:
      - opencti
